### ISSUE TITLE
Support libbi export to grid

### ISSUE THREAD

**Issue by plord12** [CJNE/ha-myenergi#442] opened 2023-10-26 12:23 UTC
**Is your feature request related to a problem? Please describe.**

Since libbi 5.408 ( https://support.myenergi.com/hc/en-gb/articles/19276846239377-libbi-Firmware-Version-5-408 ) libbi supports export to grid. This is useful if you wanted to use your libbi to charge by cheap electricity (or solar) and export when export prices are high.

**Describe the solution you'd like**

HA entity to turn on and off export to grid.

**Describe alternatives you've considered**

none

**Additional context**

Also raised https://github.com/CJNE/pymyenergi/issues/18 for the underlying library

**Comment by videojedi** [comment] 2023-10-26 12:53
Looks like the endpoints are...

to turn on
`https://s18.myenergi.net/cgi-libbi-mode-L24047041-5`

and to turn off
`https://s18.myenergi.net/cgi-libbi-mode-L24047041-1`

It's not a very consistent API is it!

**Comment by trizmark** [comment] 2023-10-29 06:20
I've got it working locally; will be posting it here soon.

The API is sort of consistent. Looking at the app code there are a number of modes that are defined, but not used and cannot be set. (capture, charge, match)
The new mode (drain) was simply added to the list and that's why it became 5.

**Comment by trizmark** [comment] 2023-10-29 06:59
Charge target is implemented as well, but it's super-broken in the libbi firmware. 😞

**Comment by plord12** [comment] 2023-10-29 07:46
> Charge target is implemented as well, but it's super-broken in the libbi firmware. 😞

Nice :-)  I'll try it with the app tonight.

BTW do you have 5.414 installed on your libbi ? ( see https://myenergi.info/libbi-no-longer-fully-charging-with-cheap-rate-ove-t11328.html )

**Comment by trizmark** [comment] 2023-10-29 07:49
I had 5.408 on until this morning. Overnight, instead of my set 2.5h charge, the libbi only charged for an hour and then it sort of held the SoC.
I installed 5.414, which now completely broke the charge from grid. Grrrr!

**Comment by trizmark** [comment] 2023-10-29 20:56
For those who are foolish and reckless.... I present you the latest bleeding edge version of the integration.
New operation mode for your libbi: '**Export**'. Let me know if you have any issues with it.
[myenergi-20231029.tgz](https://github.com/CJNE/ha-myenergi/files/13199215/myenergi-20231029.tgz)

I am adding the service to set the charge target. New version probably tomorrow (depending on my schedule).

**Comment by videojedi** [comment] 2023-10-29 22:04
Great work. I'm running 5.414. 

Can confirm export works!

Guess you've fixed the chargefromGrid bug too.... Although when switching it back on, I notice the charge level is set to zero?

Seems to be the endpoint for setting targetEnergy?

> https://myaccount.myenergi.com/api/AccountAccess/xxxxxxxx/TargetEnergy?targetEnergy=15300

**Comment by trizmark** [comment] 2023-10-29 22:17
My charge target remains the same with toggling the charge from grid. Does yours change?

**Comment by videojedi** [comment] 2023-10-29 22:33
Yes mine seems to default to zero...

**Comment by videojedi** [comment] 2023-10-29 22:37
Same behaviour in the app too...... toggle it and it returns to zero.

**Comment by videojedi** [comment] 2023-10-29 22:44
aha.... this is another shared account issue. If I login into app with primary account details, then it remembers the chargetarget between toggles...

**Comment by trizmark** [comment] 2023-10-29 22:55
If it's the same issue in the app, then it's a myenergi issue.

**Comment by trizmark** [comment] 2023-10-30 10:55
I have tested it with my secondary account and it is indeed a myeneri backend issue. 🤦

**Comment by plord12** [comment] 2023-10-30 13:15
> For those who are foolish and reckless.... I present you the latest bleeding edge version of the integration.
> New operation mode for your libbi: '**Export**'. Let me know if you have any issues with it.
> [myenergi-20231029.tgz](https://github.com/CJNE/ha-myenergi/files/13199215/myenergi-20231029.tgz)

FYI, didn't work for me, plugin failed to startup.  I see in the logs -

```
2023-10-30 13:09:29.625 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Home for myenergi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myenergi/__init__.py", line 53, in async_setup_entry
    conn = await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myenergi/pymyenergi/connection.py", line 40, in __init__
    self.oauth.authenticate(password=self.app_password)
  File "/usr/local/lib/python3.11/site-packages/pycognito/__init__.py", line 478, in authenticate
    tokens = aws.authenticate_user(client_metadata=client_metadata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycognito/aws_srp.py", line 269, in authenticate_user
    response = boto_client.initiate_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 936, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1007, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter AuthParameters.USERNAME, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

Rolled back to official version and it started up.

**Comment by trizmark** [comment] 2023-10-30 13:19
As this version adds the OAuth endpoints you need to remove your integration and re-add it as it requires both API key/password and App email/app password parameters.

**Comment by plord12** [comment] 2023-10-30 14:49
> As this version adds the OAuth endpoints you need to remove your integration and re-add it as it requires both API key/password and App email/app password parameters.

Ah, got it, thanks.  After re-adding ( and entering username/password ) I was able to enable export :-)

My grid charge percentage stayed at 60% FYI.

**Comment by trizmark** [comment] 2023-10-30 15:03
Great to hear!
The charge target is only an issue if you're using a secondary account to access your main account.
People who signed up to a myenergi account using google/apple/facebook need a secondary account as currently we only support OAuth with email/password combo.

I am nearly ready with the charge target setting functionality, but as this is the first time I'm implementing a HA service, it is a lot of trial and error.

**Comment by whittyone** [comment] 2023-12-30 21:49
Thanks for making this version. Is there a plan for getting a 0.0.25 made with this in? 
(Sorry, I'm not sure how that side is managed)
Thanks

**Comment by trizmark** [comment] 2024-01-09 10:53
@whittyone Yes, there is. I am updating the pymyenergi library currently. Once that's done and out, I can push my modifications to the HA component.

**Comment by plord12** [comment] 2024-02-19 10:19
I see this didn't make 0.0.25

**Comment by trizmark** [comment] 2024-02-19 10:24
@plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

**Comment by plord12** [comment] 2024-02-19 10:33
> @plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

Brilliant!  Many thanks.

**Comment by MaximumFish** [comment] 2024-02-19 10:42
I'm making really good use of this to dump excess power in the evenings and during Octopus saving sessions, so good to know that I shouldn't upgrade just yet. Thanks!

**Comment by MaximumFish** [comment] 2024-03-14 11:07
> @plord12 The 0.1.0 version of pymyenergi (released yesterday) has all the necessary features in there, so once I rebase my local dev copy to 0.0.25, this will be in 0.0.26.

Did this get added to 0.0.26 or 0.0.27? I don't see it in the changelogs.

**Comment by plord12** [comment] 2024-04-14 10:27
I hate to pester, given so many give their time for projects like this, but any news ?

Once this gets in I hope to look at the libbi dual tariff issue (eg sync libbi schedule from octopus) ... but I don't really want to get going until this is in.

Cheers :-)

**Comment by trizmark** [comment] 2024-04-26 08:15
I can see the light at the end of the tunnel!
I've been playing catch-up with the changes that happened in this repo vs what I've added. Hoping to submit the PR this weekend. 🤞

**Comment by MalcolmSpencer** [comment] 2024-04-27 07:21
@trizmark would you be able to look at issue #516 when you do your update? Currently, Libbi operating mode is not working in 0.0.27 but the solution is described. 

Thanks,

**Comment by trizmark** [comment] 2024-04-27 08:19
I found that issue when I brought my fork up to 0.0.27 and it's already fixed.

**Comment by trizmark** [comment] 2024-05-01 11:25
Ok folks, here's the pre-release. Few things to tweak, but I've been running this for a few days and had no issues with it.
Could someone with a Zappi verify that I didn't break functionality that has been added since 0.0.24? @videojedi Do I remember correctly that you have a Zappi?

Just to highlight the main changes:
- libbi charge from grid switch
- libbi 'export' operating mode
- libbi set charge target service

I still need to add the app email/password to the reconfigure screen (so you won't have to remove the addon and readd it), but other than that I think we're there!

[myenergi-20240501.tgz](https://github.com/CJNE/ha-myenergi/files/15176531/myenergi-20240501.tgz)

**Comment by plord12** [comment] 2024-05-01 12:06
Brilliant !

I've installed it, so far so good.  I'll know more after 24 hours though.

( BTW myenergi-20240501.tgz seems to be a tar file not a compressed tar file )

**Comment by trizmark** [comment] 2024-05-01 12:49
One thing I forgot to mention: setting the charge target does not seem to be reflected in the ME mobile app. I'm on Android, using 3.3.2 (rev. 41) version of the app and it does not reflect the changes I do via the API. The new charge target is taken into account (based on my testing), but the app will cache whatever value you set there. 🤷

**Comment by videojedi** [comment] 2024-05-01 16:50
Great work! Thanks for your efforts. I can confirm my Zappis are still functioning.

Now the weather is getting nicer, I plan to switch the charge from grid on or off based on solar prediction for the following day.

Will keep an eye on it and report back any/if issues.

**Comment by plord12** [comment] 2024-05-02 07:44
> I've installed it, so far so good. I'll know more after 24 hours though.

Overnight automations wored as expected :-)

**Comment by videojedi** [comment] 2024-05-02 08:48
Yep all my automations worked too. Looked at 8am and was slightly worried Libbi was Stopped. But then realised Octopus had given me cheap rate for 12.5 hours! Automation switched Libbi back to normal when cheap rate ended as intended. 
Cheers.

**Comment by trizmark** [comment] 2024-05-08 12:50
I assume everything is still working. I am just finishing off improving the UX when moving from the current version to the new one that will support OAuth - don't really want to tell users to remove the integration and re-add it to enter the app email/password.

**Comment by trizmark** [comment] 2024-05-14 13:42
The pymyenergi PR is in. 🎉 
Once that's merged I can submit the PR for this as it is fully ready!
When the new version is out, you can simply hit 'reconfigure' on the integration, add app email/password and boom; you got all the new features. Pretty proud of the user experience handling... 😁

**Comment by MaximumFish** [comment] 2024-05-15 11:08
Awesome news! Not sure I need to do the new login if I'm using the test version from earlier in the thread? But I look forward to seeing it as available soon either way. Good job! 😀

**Comment by trizmark** [comment] 2024-05-15 11:17
> Awesome news! Not sure I need to do the new login if I'm using the test version from earlier in the thread? But I look forward to seeing it as available soon either way. Good job! 😀

You won't need it. The 'Reconfigure' will only be required if you're upgrading from the official 0.0.27 version.

**Comment by githubjonny** [comment] 2024-06-01 08:36
Hi, I just wondered what the sensor was for the charge and set target charge? I can set stopped, normal and export but can't find the new charge / set charge target.

**Comment by trizmark** [comment] 2024-06-02 21:45
> Hi, I just wondered what the sensor was for the charge and set target charge? I can set stopped, normal and export but can't find the new charge / set charge target.

Use the myenergi_libbi_charge_target service to set the charge target of the libbi.

**Comment by githubjonny** [comment] 2024-06-02 22:40
Strange, I don't seem to have that. Can you share a screenshot in assistant of that service?

**Comment by trizmark** [comment] 2024-06-03 08:44
In order to see that you need to use the currently unreleased version that's included further up here.
I'm waiting for my PR to be accepted for pymyenergi and once that's done I can submit my PR for ha-myenergi, which would include this functionality in the official release.

**Comment by MalcolmSpencer** [comment] 2024-06-09 07:18
@trizmark it looks like the pymyenergi change has been made in 0.2.0 would it be possible to get this great new functionality included in ha-myenergi?

**Comment by MaximumFish** [comment] 2024-06-20 09:13
I don't know why because the old test version still works fine, but I'm checking for the update every day.

**Comment by MalcolmSpencer** [comment] 2024-06-22 11:46
I was waiting for the official HACs version but I think I will install the test version that supports charging. Silly question (but I'm fairly new to HA) how do you install the test version?

**Comment by MaximumFish** [comment] 2024-06-23 12:03
I don't think the Libbi supports on-demand charging? Or at least not yet. It does some weird thing with Agile tariffs where at 4pm it gets the next day's cheapest periods and charges itself at those times, but there's no way to forcibly charge it.

**Comment by Future-Surfer** [comment] 2024-06-24 08:15
Also waiting patiently for this release :)

In related news, wonder whether this beta testing will have any ramifications for this integration: https://myenergi.info/libbi-beta-testing-signup-t13284.html

**Comment by plord12** [comment] 2024-06-24 09:53
> In related news, wonder whether this beta testing will have any ramifications for this integration: https://myenergi.info/libbi-beta-testing-signup-t13284.html

Good point ... I signed up, but I guess the server API will remain the same so that phone app remains working,.  Could have more features I suppose.

**Comment by plord12** [comment] 2024-06-24 09:55
> I don't think the Libbi supports on-demand charging? Or at least not yet. It does some weird thing with Agile tariffs where at 4pm it gets the next day's cheapest periods and charges itself at those times, but there's no way to forcibly charge it.

You can automate with home assistant ... something like -

```
alias: Electricity Rule 1a - start charging battery from grid (offpeak + intelligent)
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.octopus_energy_a_xxxxxxxx_intelligent_dispatching
    from: "off"
    to: "on"
condition: []
action:
  - service: retry.call
    target:
      entity_id: select.myenergi_libbi_operating_mode
    data:
      service: select.select_option
      option: Normal
      on_error:
        - service: script.debug
          data:
            message: Rule 1a:Failed to set libbi to Normal
  - service: retry.call
    target:
      entity_id: switch.myenergi_libbi_charge_from_grid
    data:
      service: switch.turn_on
      on_error:
        - service: script.debug
          data:
            message: Rule 1a:Failed to set libbi to charge from grid
mode: single
```

**Comment by MaximumFish** [comment] 2024-06-24 10:54
> You can automate with home assistant ... something like -

I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.

Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

**Comment by githubjonny** [comment] 2024-06-24 11:34
> > You can automate with home assistant ... something like -
> 
> I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.
> 
> Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

I literally just thought the same thing. However, if 'normal' was converted to charge using that method, what mode would you use to discharge to the house (not discharge as that goes to the grid and house until bat is depleted)

**Comment by MalcolmSpencer** [comment] 2024-06-24 11:49
you can always force it to charge manually when in normal mode, just manually set the tariff at a low rate in the required slots, set the SOC to the desired level and enable charge from grid. I just need to be able to automate this in HA. I don't think PYMyenergi 0.2.0 supports setting the tariff so I will just leave it at a flat tariff for the whole day and then use the service calls to set the  SOC and enable charge from grid.

**Comment by plord12** [comment] 2024-06-24 11:57
> > You can automate with home assistant ... something like -
> 
> I could be mistaken but I don't think that does what you think it does. I'm pretty sure it just toggles the preference to enable grid charging _on a schedule based on your tariff_. The same toggle that you find in the app under the Charging Preference drop-down.
> 
> Though now that I've typed that out perhaps it could be fudged by setting the entire day as off-peak and then toggling that preference on and off....? 🤔

Yes, you need to disable the tariff (I set every 1/2 hour to 7.5p).  The above has been working for me with the "pre-release" plugin mentioned here.

You can also do things like export the battery before offpeak starts.

I did a talk recently to U3ACommunities on my setup - see https://plord.co.uk/talks/how-to-reduce-your-electricity-bill-to-zero/

**Comment by MaximumFish** [comment] 2024-06-24 12:07
Ooo, I'll have a look at that! Thanks.

**Comment by githubjonny** [comment] 2024-06-24 15:10
> I did a talk recently to U3ACommunities on my setup - see https://plord.co.uk/talks/how-to-reduce-your-electricity-bill-to-zero/

Just been watching that for the last hour, looks like you have done virtually the same as me. One thing you may find helpful is a page I set up to work out what size battery would be best for me. I'll not go into it in detail on here since its nothing to do with this module but url is eoob.co.uk.

**Comment by plord12** [comment] 2024-06-24 15:29
> One thing you may find helpful is a page I set up to work out what size battery would be best for me. I'll not go into it in detail on here since its nothing to do with this module but url is eoob.co.uk.

Many thanks for sharing.

**Comment by MaximumFish** [comment] 2024-06-24 15:35
Yes, our setups are very similar but I'd not twigged that I could trick the Libbi into charging "out of hours" like that, so I'll make that change on my end for sure.

**Comment by plord12** [comment] 2024-06-24 15:50
> Yes, our setups are very similar but I'd not twigged that I could trick the Libbi into charging "out of hours" like that, so I'll make that change on my end for sure.

Off topic, I know, but still useful.

One thing I eventually did was to have counters "minutes to xxx" and "minutes since xxx".  Eg -

```
template:
  - sensor:
    - name: "Minutes to start of cheap rate"
      unique_id: minutes_to_start_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(states('input_datetime.octopus_start_of_offpeak'),"%H:%M:%S")|as_timestamp() - strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
    - name: "Minutes to end of cheap rate"
      unique_id: minutes_to_end_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(states('input_datetime.octopus_end_of_offpeak'),"%H:%M:%S")|as_timestamp() - strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
    - name: "Minutes since start of cheap rate"
      unique_id: minutes_since_start_of_cheap_rate
      unit_of_measurement: "min"
      state: >
        {% set diff=(strptime(now().strftime("%H:%M:%S"),"%H:%M:%S")|as_timestamp() - strptime(states('input_datetime.octopus_start_of_offpeak'),"%H:%M:%S")|as_timestamp())/60  %}
        {% if diff < 0 %}
        {{ (24*60)+diff }}
        {% else %}
        {{ diff }}
        {% endif %}
```

where input_datetime.octopus_start_of_offpeak is stored when the interation changes (sometimes binary_sensor.octopus_energy_electricity_xxxxx_off_peak is not known) -

```
alias: Octopus - store offpeak end
description: ""
trigger:
  - platform: state
    entity_id:
      - >-
        binary_sensor.octopus_energy_electricity_xxxxx_off_peak
    attribute: current_end
    not_to:
      - unknown
      - unavailable
action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: >
        {{
        ((state_attr('binary_sensor.octopus_energy_electricity_xxxxxx_off_peak',
        'current_end')- timedelta(seconds=30))|as_local()) }}
    target:
      entity_id: input_datetime.octopus_end_of_offpeak
mode: single
```

You can then figure out when to start exporting your saved solar before offpeak starts -

```
alias: Electricity Rule 3 - export battery before cheap rate
description: >-
  0.6 slightly too early (5% left), 0.7 about right (0% left).  Cant export
  whilst charging car, but possibly could if charging is completed.
trigger:
  - platform: template
    value_template: >-
      {% if states('sensor.myenergi_libbi_soc')|is_number and
        states('sensor.minutes_to_start_of_cheap_rate')|is_number
      %} {{ (states('sensor.myenergi_libbi_soc')|float)*0.68 >
      states('sensor.minutes_to_start_of_cheap_rate')|float }} {% endif %}
condition:
  - condition: state
    entity_id: select.myenergi_libbi_operating_mode
    state: Normal
  - condition: numeric_state
    entity_id: sensor.minutes_to_start_of_cheap_rate
    above: 1
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.myenergi_zappi_xxxx_plug_status
        state: EV Connected
      - condition: state
        entity_id: sensor.myenergi_zappi_xxxxx_plug_status
        state: Charging
action:
  - service: script.debug
    metadata: {}
    data:
      message: >-
        Rule 3: Started export - minutes to start of cheap rate {{
        states('sensor.minutes_to_start_of_cheap_rate') }} soc {{
        states('sensor.myenergi_libbi_soc') }} %
  - service: retry.call
    target:
      entity_id: select.myenergi_libbi_operating_mode
    data:
      service: select.select_option
      option: Export
      on_error:
        - service: script.debug
          data:
            message: Rule 3:Failed to set libbi to Export
mode: single
```

I found you had to be careful not to import & export at the same time (eg discharge battery & charge car).

**Comment by MaximumFish** [comment] 2024-06-24 16:36
Oh that's a cool way to do it. Currently I've blocked out certain times through the evening to export, so at 20:30 it exports down to 50%, at 21:30 take it down to 25%, and so on. My thinking being that people are largely still awake at those times and while it's not the point of highest demand, it's still going to be used energy.

I've worked around the car issue by having the export stop if the car's plugged in and "intelligent dispatch" turns on. And I've worked around it exporting _into the car_ by setting the export margin on the Zappi to be really high. Previously I'd set it to switch the Zappi to stopped if either the car is already plugged in when the trigger fires, or if there's an active export and the car goes from unplugged to plugged in.

(I hope trizmark doesn't mind us discussing all of this in a bug report!)

**Comment by MaximumFish** [comment] 2024-06-24 19:01
> Yes, you need to disable the tariff (I set every 1/2 hour to 7.5p)

Wondering how you managed this... If I do the same it complains that I've only set one rate and won't let me save it, and if I set it to a single rate tariff it removes the option to grid charge completely.

**Comment by ragg987** [comment] 2024-06-24 19:38
> Edit: Never mind, I was able to set it from the website rather than the app. Remove the empty row of peak slots and that did the trick.

Yes was just about to post that - there must be additional validation on the App compared to website. The rate on the single line does not matter, it can also be a high rate line. I wonder if this is a bug that permits a workaround, if so ME could well remove it at some point. I hope they enhance the API to permit a forced charge at some point.

On that bug where the App does not show the SoC updated elsewhere, I have already raised this with ME and they have been able to replicate and added to backlog.
[https://myenergi.info/viewtopic.php?p=126458#p126458](url)

Patiently awaiting this release of the add-on to make it to HA. Thanks for sharing @plord12 , it never occured to me to export during the day and charging at bight. I also have to negotiate the splitting of FiT from SEG with Octopus - not got round to it yet. My back of a fag packet suggests I could be paid to use energy in the summer months, should partially off-set what I pay to heat (ASHP) in the winter period.

**Comment by MaximumFish** [comment] 2024-06-24 20:39
Oh god I've just made the most complicated couple of automations to turn Grid charging on and off! So many conditions to test against! Might post it tomorrow if it actually works and there's interest.

**Comment by githubjonny** [comment] 2024-06-24 22:16
Anyone know if there's a way to pull the temperature of the inverter from the libbi? Would be nice to kick a CPU fan into action when xyz temp is reached.

**Comment by MalcolmSpencer** [comment] 2024-06-25 06:10
Temperature is available on the historic data API https://s18.myenergi.net/cgi-jday-Lxxxxx-yyyy-mm-dd but not the real-time API used by the HA integration. On the historic API there is 

Inverter temp
Battery temp
Battery radiator temp
Ambient temp
Controller temp

**Comment by videojedi** [comment] 2024-07-01 08:35
> One thing I forgot to mention: setting the charge target does not seem to be reflected in the ME mobile app. I'm on Android, using 3.3.2 (rev. 41) version of the app and it does not reflect the changes I do via the API. The new charge target is taken into account (based on my testing), but the app will cache whatever value you set there. 🤷 

This seems to be the same for the iOS app. Successful charge target change from home assistant but not reported in app.

**Comment by githubjonny** [comment] 2024-07-01 22:08
> In order to see that you need to use the currently unreleased version that's included further up here. I'm waiting for my PR to be accepted for pymyenergi and once that's done I can submit my PR for ha-myenergi, which would include this functionality in the official release.

Hi @trizmark any updates from pymyenergi? Thanks again for all your hard work 👍

**Comment by trizmark** [comment] 2024-07-20 11:28
It's been a long time coming, but finally it's here!
https://github.com/CJNE/ha-myenergi/pull/553

Apologies for the delay (new job, family stuff)

**Comment by githubjonny** [comment] 2024-07-21 14:24
@trizmark great job 👍🏼 👏🏼 

I'm still getting 0.0.27 in HACS. Can't see if this has been pushed through. Anyway to jump to the latest build via HA?

**Comment by MaximumFish** [comment] 2024-07-25 09:32
Also eagerly waiting for the new release, though I note that the page for #553 says that some checks have failed?

I'm wondering if this new version will have a way to actually check and confirm the state of the "charge from grid" toggle? My automation completely failed a couple of nights ago because the myenergi API was down at 23:30 when it tried to turn on grid charging, and the "until" loop that was supposed to safeguard against failed commands was just checking the state of this toggle. It was only when I woke up to an empty battery that I realised it's just a dumb toggle and not actually read back from anywhere!

I've fixed that now by instead checking the state of `sensor.myenergi_libbi_xxxxxxxx_status` to make sure it's switched to "Target Charge", but it doesn't work for turning grid charging off in the morning due to the state changing overnight to "Full" when it's full. Turning off grid charging doesn't change this state at all (I think it needs to drop below 95% first?) and there doesn't seem to be anything else to check against.

For now I'm just going to have to toggle it and hope that the API is up and running, but it would be great to have something reliable to check against.

**Comment by MaximumFish** [comment] 2024-07-25 11:41
Hmm, it didn't work like that for me. I noticed that the API was being screwy when I went to bed at 23:00. The SoC sensor hadn't updated for a while and the ME app was showing all yellow warning triangles on everything, but I assumed my automation would take care of things when it came back up.

As it is though, HA saw a brief blip of "unavailable" that morning, but when the automation fired it was happy enough. The "until" loop thought that it had turned on successfully and the status didn't change at any point throughout the night, even after the API had come back at around 1:00. HA thought that it was on but the Libbi did not.

Of course the version I'm using is a few revisions behind the current one now, so maybe it'll work better in 0.0.28? 🤔 

![image](https://github.com/user-attachments/assets/1c17701a-55b5-487d-afb1-efa6277d11b1)
Note: The name of the automation firing at 23:30 is misleading. It now starts the grid charging, but it's a repurposed automation that would _stop_ the Libbi entirely during non-off-peak intelligent dispatch windows and the internal name didn't change along with the display name I guess.

**Comment by plord12** [comment] 2024-07-30 07:13
> Hmm, it didn't work like that for me. I noticed that the API was being screwy when I went to bed at 23:00. The SoC sensor hadn't updated for a while and the ME app was showing all yellow warning triangles on everything, but I assumed my automation would take care of things when it came back up.

We need a local API.  

I've raised support requests to myenergi to this effect.  The more of us who do the same the better.

**Comment by trizmark** [comment] 2024-07-30 07:45
@MaximumFish I'll do some more testing to see how the integration behaves during an API outage.
@plord12 Fully agree with you, local API all the way! In fact, I implemented local monitoring by tapping into the Modbus interface. It doesn't give me control, but I can see everything real-time and have access to data that's not exposed via the API.

**Comment by MaximumFish** [comment] 2024-07-30 11:59
That would be awesome, thank you.

It's not a huge issue right now as the only times I've ever had issues is overnight when switching grid charging _on_ and I can check that's worked via the "Target Charge" state. In the mornings I'm currently just checking the app manually to make sure it's turned off properly. Though I wonder if I can do something funky with watching the grid draw to figure out if it's switched or not...

@plord12 if I were to raise the local API issue too, what would I be asking for exactly? I don't think I'd get away with just saying "Local API plz" :)

**Comment by plord12** [comment] 2024-07-30 14:05
> @plord12 if I were to raise the local API issue too, what would I be asking for exactly? I don't think I'd get away with just saying "Local API plz" :)

I would say something like -

"There have been several times recently that I've been unable to control my myenergi devices .. a couple of cases where my internet connection was unreliable and a couple where the myenergi server didn't seem to respond.  Regardless of the cause, its vital I can control the myenergi devices at all times.  I've read that most manufacturers provide a "local API" to make this work.  

I see companies like Octopus are giving out such devices for free.

Can you raise an enhacement request to provide a (documentend) local API and update the app to use it when possible.

Of course, once this exists, 3rdaprty tools such as home assistant can also make use of it"

**Comment by trizmark** [comment] 2024-07-30 14:36
You can also highlight the fact that if the integrations switch to local API, then they could save on AWS costs!

**Comment by MaximumFish** [comment] 2024-07-30 15:30
Cool, I'll send something in to add to the pile!

**Comment by githubjonny** [comment] 2024-08-06 20:19
Hi @CJNE, do we have an ETA for the update? Be fantastic to take advantage of the charge feature for the libbi (opens up some massive savings)

**Comment by githubjonny** [comment] 2024-08-19 12:49
Can anyone give me a rough guide on upgrading before the latest version is officially released? Got caught out with a scheduled charge today (left over from yesterday's free electric 1-2pm).

**Comment by githubjonny** [comment] 2024-08-20 18:50
@trizmark Thank you. I just went to do this now and saw that the update was available in HA :) Ran the update and all went well. However, I can't seem to get the libbi to charge using the "on" toggle on switch.myenergi_libbi_XXXXXX_charge_from_grid (removed id). Clicking doesn't seem to do anything. I then re-read the release notes and saw :

"In order to access the new functionality, the integration requires the app email and password (to access the OAuth controlled API calls). This can simply be done by 'Reconfiguring' the integration. The app email and password is optional and only required if someone owns a libbi."

I think this may be an issue for me as I use a google login for my myenergi account. Any ideas?

**Comment by trizmark** [comment] 2024-08-20 19:10
@githubjonny We found a workaround for that! So, you need to create a new ME account with email and pass and invite this new account to manage your house. The component already caters for this (there's an invitation ID in the API that needs to be saved/passed on) and it works fine.

**Comment by githubjonny** [comment] 2024-08-20 19:30
@trizmark thanks for your help with this. I'll do that 1st thing tomorrow. It's interesting I can control the libbi discharge without a standard login though. Wonder if there's a way to control charging with just the API etc.

**Comment by ragg987** [comment] 2024-08-20 19:36
You can also use your original email and user it to create an account with
a password, no need to add another account/email. The ME portal recognises
it as being the same. This method worked for my original Google login.

Looking forward to installing this upgrade, thank you.

**Comment by githubjonny** [comment] 2024-08-20 19:41
see this is why I love open source software. Within a few minutes had two replies both offered solutions. 

I just created a new account and can confirm what @ragg987 said works. As soon as I created the account and logged in it had all my details.

Thanks again everyone.

**Comment by githubjonny** [comment] 2024-08-20 19:52
Just an update, @trizmark I now can control the charge from the grid toggle :) thanks for your hard work on that one 👍🏼

Just wondered what everyone's doing regarding half hour time slots? I'm assuming two tier pricing with all half hours on the cheap tariff? 

Although, now I've said that 'out loud', I guess just one tariff is only needed (assuming ME allows charging on a single tariff).

**Comment by trizmark** [comment] 2024-08-20 20:24
@githubjonny Yeah, two tier pricing and all the slots on the cheap tarriff. That way you can toggle the charge from grid on and off to control when the libbi charges.
> Wonder if there's a way to control charging with just the API etc.
The ME API uses two different authentication methods. Most of the old sutff uses digest (based on API key/secret) and some of the new stuff uses OAuth (based on username/password). The ME engineers hinted on the forums that they're planning to move everything over to OAuth, but it looks like that'll take a long time. The mode selection API call is based on old auth (which worked without app email/pass), but charging from grid toggle and charge target setting API calls are based on new auth (which didn't work).

**Comment by githubjonny** [comment] 2024-09-07 00:27
> Temperature is available on the historic data API https://s18.myenergi.net/cgi-jday-Lxxxxx-yyyy-mm-dd but not the real-time API used by the HA integration. On the historic API there is 
> 
> Inverter temp
> Battery temp
> Battery radiator temp
> Ambient temp
> Controller temp
> 
> 

Any guides on how to achieve this anywhere online?

**Comment by Future-Surfer** [comment] 2024-09-08 14:55
Now that we can change operating mode to 'export', do we think there is any scope for setting/limiting charge/discharge rates?

**Comment by githubjonny** [comment] 2024-09-08 15:57
That would be handy if possible. Currently I export my battery before the cheap session starts at a low amp rate (to help battery life). However would prefer to dump battery much quicker during octopus saving session without having to alter settings manually

**Comment by trizmark** [comment] 2024-09-08 16:57
Limiting charge/discharge rates is a no-go at the moment. While technically it would be possible, the feature is not implemented by the controller and it's not exposed via the API.
I can clearly see the modbus messages from the libbi controller that instruct the inverter as to what rate to charge/discharge with, but that's not useful at the moment.

**Comment by trizmark** [comment] 2024-09-08 16:58
> > Temperature is available on the historic data API https://s18.myenergi.net/cgi-jday-Lxxxxx-yyyy-mm-dd but not the real-time API used by the HA integration. On the historic API there is
> > Inverter temp
> > Battery temp
> > Battery radiator temp
> > Ambient temp
> > Controller temp
> 
> @MalcolmSpencer , Any guides on how to achieve this anywhere online?

Are you hoping to have this data in HA or just in general? I could add this to pymyenergi, but I don't think there's a way to add historical data to HA (well, not without touching the DB directly).

**Comment by Future-Surfer** [comment] 2024-09-08 17:32
> While technically it would be possible, the feature is not implemented by the controller and it's not exposed via the API. 

That makes sense. Would be able to tell whether this sort of thing (limiting charge/discharge) is within the realm of possibility for myenergi to expose via the API at some point? Just want to have an idea of where to set my expectations :)

**Comment by trizmark** [comment] 2024-09-11 09:43
Possibly at some point, but I don't see that being in the next 12 months. I know they're reworking the libbi controller firmware. Not sure how big the controller FW is and how much space there is for extra features. After all, it's only an ESP32 doing an awful lot of things.

**Comment by G6EJD** [comment] 2024-09-29 09:02
Why hasn’t this ’issue’ been closed? It’s become a rambling set of comments.

**Closed** 2024-09-29 09:39 UTC
