### ISSUE TITLE
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x70ff42e77dd0>,)

### ISSUE THREAD

**Issue by ProximusAl** [CJNE/ha-myenergi#577] opened 2024-09-04 21:12 UTC
New version of HomeAssistant docker now throws this…

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x70ff42e77dd0>,) inside the event loop by custom integration 'myenergi' at custom_components/myenergi/__init__.py, line 107: await self.client.refresh() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/cjne/ha-myenergi/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/myenergi/__init__.py", line 60, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/myenergi/__init__.py", line 107, in _async_update_data await self.client.refresh()

**Comment by MalcolmSpencer** [comment] 2024-09-07 08:23
I got the same 

running on Pi4
Core 2024.9.1
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240906.0
MyEnergi V0.0.28

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 09:12:41 (1 occurrences)
Last logged: 09:12:41

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f60de29d0>,) inside the event loop by custom integration 'myenergi' at custom_components/myenergi/__init__.py, line 55: await conn.discoverLocations() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/cjne/ha-myenergi/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/myenergi/__init__.py", line 55, in async_setup_entry await conn.discoverLocations()

**Comment by trizmark** [comment] 2024-09-08 16:53
I haven't upgraded yet to see this error, but the fix looks simple enough. I'll try to bump my dev HA to the latest version and create a PR.

**Comment by markruys** [comment] 2024-09-13 16:19
> I haven't upgraded yet to see this error, but the fix looks simple enough. I'll try to bump my dev HA to the latest version and create a PR.

Glad the fix looks simple enough, for me the best way to fix it is unclear yet :) I would say the issue is in [pymyenergi](https://github.com/CJNE/pymyenergi/blob/main/pymyenergi/connection.py#L112). In [Blocking operations with asyncio](https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs) a few helpers are suggested, like `homeassistant.helpers.httpx_client.get_async_client()`.

**Comment by YanisKyr** [comment] 2024-09-27 08:54
Got the same today - if you need more logs or diagnostics let me know.

**Comment by trizmark** [comment] 2024-10-09 14:13
I started looking at the issue, but the fix might not be that simple. In order to move the currently blocking operation out of the event loop, the suggestion from the HA devs is to use a httpx_client helper from the homeassistant library. Which ideally we want to avoid as the blocking call happens in pymyenergi, which shouldn't depend on homeassistant.

I'll keep looking for other ways to solve this.

**Comment by trizmark** [comment] 2024-10-09 16:24
So I thought I could simply change the code to:
```
await hass.async_add_executor_job(conn.discoverLocations)
```
however, this results in the following error:
```
2024-10-09 17:18:22.138 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:1975: RuntimeWarning: coroutine 'Connection.discoverLocations' was never awaited
  handle = self._ready.popleft()
```

Strange as the same approach (async_add_executor_job) works fine in other parts of code.

**Comment by CJNE** [comment] 2024-10-16 20:29
Thanks for trying to figure this out!
Home Assistant seems to prefer to use the same httpx client session for all http calls, this is more efficient and can help performance. 

So i've made some changes, first i added a way for us to pass the httpx.AsyncClient we can get from HA to the pymyenergi Connection instance, and changed the http calls to re-user the client instead opening/closing the connection for each invokation.

Then i modified the integration setup to get httpx.AsyncClient from the HA helper function and pass it to the pymyenergi Connection constructor.

It all seems to work fine, the warning is gone :)

**Closed** 2024-10-16 20:28 UTC

**Comment by markruys** [comment] 2024-10-17 06:36
Nice work @CJNE!
