### ISSUE TITLE
Add support for libbi

### ISSUE THREAD

**Issue by plord12** [CJNE/ha-myenergi#395] opened 2023-08-12 11:21 UTC
**Is your feature request related to a problem? Please describe.**
Add support for the libbi battery

**Describe the solution you'd like**
Full integration to libbi, inc charge status, charge from grid, charge from solar, integration into Energy dashboard etc

**Describe alternatives you've considered**
None

**Additional context**
I see some API info is available here https://myenergi.info/libbi-api-t9910.html

**Comment by Future-Surfer** [comment] 2023-08-18 10:04
another vote for this feature please. Happy to be a guinea pig if required :)

**Comment by videojedi** [comment] 2023-08-18 10:44
Me too. Happy to test, libbi fitted yesterday.

**Comment by simonjgreen** [comment] 2023-09-08 07:16
Because myenergi don't officially operate a public API[](https://support.myenergi.com/hc/en-gb/articles/5069627351185-How-do-I-get-an-API-key-)  this hampers development against new products they release. There is active discussion reverse engineering the libbi portion of the API on their forum[](https://myenergi.info/libbi-api-t9910.html) . This add-on utilises the pymyenergi[](https://github.com/CJNE/pymyenergi)  upstream library which is there you may want to redirect requests for libbi support. 

(I would also love to have libbi in home assistant!)

**Comment by plord12** [comment] 2023-09-12 14:25
There is a pull request for pymyenergi here https://github.com/CJNE/pymyenergi/pull/10 FYI

**Comment by videojedi** [comment] 2023-09-12 17:49
It's been accepted.  :) I've not got my head around the integration with this repo and home assistant yet... maybe someone can have a go....?

pymyenergi can now read some basic values from the libbi including state of charge and solar PV ct values. 
You can also set the mode (Stopped or normal) and set the priority.

However the ellusive 'charge from grid' command is proving tricky as it seems to talk to the front end server and not the back end like all the other commands.... 
Probably because the front end is actually turning the grid charging on and off according to the tariff schedule. I've tried guessing what the actual backend endpoint might be, but not luck yet.

**Comment by CJNE** [comment] 2023-09-12 21:19
> It's been accepted. :) I've not got my head around the integration with this repo and home assistant yet... maybe someone can have a go....?
> 
> pymyenergi can now read some basic values from the libbi including state of charge and solar PV ct values. You can also set the mode (Stopped or normal) and set the priority.
> 
> However the ellusive 'charge from grid' command is proving tricky as it seems to talk to the front end server and not the back end like all the other commands.... Probably because the front end is actually turning the grid charging on and off according to the tariff schedule. I've tried guessing what the actual backend endpoint might be, but not luck yet.

Getting the basic functionality into pymyenrgi is a very good start on this, the next step would be to add the entities needed for HA, if someone is up for it it should be pretty straightforward to mimic for example the Zappi entities and tweak accordingly to what the Libbi uses. 
I can pick it up when I get some time but unfortunately I don't have much of that at the moment :)

**Comment by trizmark** [comment] 2023-09-15 09:36
I am having a stab at this (as I got my libbi installed yesterday)...
![Screenshot 2023-09-15 at 10 32 52](https://github.com/CJNE/ha-myenergi/assets/36660435/2c87b550-258f-4ff5-a91f-18ec2db874b6)

**Comment by videojedi** [comment] 2023-09-15 10:01
Excellent. Have you forked anywhere we can test?

**Comment by trizmark** [comment] 2023-09-15 10:12
@videojedi https://github.com/trizmark/ha-myenergi/tree/add-libbi-support
Added SoC, voltage, frequency and some of the CTs. Will do some more work later.

**Comment by videojedi** [comment] 2023-09-15 11:12
Amazing work!!

**Comment by Future-Surfer** [comment] 2023-09-15 12:48
apologies if this is a daft question, I had the myenergi custom integration already installed and its currently version 0.0.23.

Do I need to do anything in particular to get the libbi device/entities to show up?

**Comment by trizmark** [comment] 2023-09-15 13:25
@Future-Surfer Grab the updated code from my fork: https://github.com/trizmark/ha-myenergi/tree/add-libbi-support
Use the custom_components/myenergi directory and replace your current integration with it.
In case that's too complicated, I've attached a snapshot of the integration, which you can use to replace your current one.
[myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12619740/myenergi.tgz)

Once I've added all the entities and tested the updates, I'll submit a PR and once that's been merged the update will also show up in HACS.

**Comment by trizmark** [comment] 2023-09-15 13:54
Added more stuff to the integration. You can set the priority and the operating mode, though the mode selection seems to be bugged. You can issue a stop, but going back to 'normal' doesn't seem to work. The logbook entry is also missing about the state change. First time messing around with HA integrations, so bear with me....
As my libbi is my vHub there's a clash between the unique IDs generated for the FW version and Serial Nr, so they're missing from the libbi entity, but they're present for 'My Home' (which is the vHub).
![Screenshot 2023-09-15 at 14 51 10](https://github.com/CJNE/ha-myenergi/assets/36660435/130aceee-58b6-4d5a-82f2-4f362751b7a8)

**Comment by videojedi** [comment] 2023-09-15 14:17
will check the mode stuff again, probably my fault!

**Comment by trizmark** [comment] 2023-09-15 14:34
> will check the mode stuff again, probably my fault!

It works fine using pymyenergi directly (myenergi libbi mode Normal), so I fairly certain it's the integration code.

**Comment by trizmark** [comment] 2023-09-15 15:08
Ok, so I think it's to do with the various status mappings. We try to equate 0 to Stopped and 1 to Nomal (just how the cgi-libbi-mode endpoint expects it), but right now my libbi is returning 102.
I was wondering if we should use the 'lmo' property rather than the 'sta' property. lmo reads 'local mode of operation' to me and it switches between 'BALANCE' (which is on) and 'STOP' (which is off).

**Comment by Future-Surfer** [comment] 2023-09-15 15:26
> @Future-Surfer Grab the updated code from my fork: https://github.com/trizmark/ha-myenergi/tree/add-libbi-support Use the custom_components/myenergi directory and replace your current integration with it. In case that's too complicated, I've attached a snapshot of the integration, which you can use to replace your current one. [myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12619740/myenergi.tgz)
> 
> Once I've added all the entities and tested the updates, I'll submit a PR and once that's been merged the update will also show up in HACS.

Appreciate the handholding! Successfully got it updated and working. Will keep an eye on the thread and test out any other updates you guys make :)

**Comment by videojedi** [comment] 2023-09-15 23:34
Sounds like a plan. I’ll add lmo as well  Just trying to figure out the energy totals. Sent from my iPhoneOn 15 Sep 2023, at 16:09, Zoltan ***@***.***> wrote:﻿
Ok, so I think it's to do with the various status mappings. We try to equate 0 to Stopped and 1 to Nomal (just how the cgi-libbi-mode endpoint expects it), but right now my libbi is returning 102.
I was wondering if we should use the 'lmo' property rather than the 'sta' property. lmo reads 'local mode of operation' to me and it switches between 'BALANCE' (which is on) and 'STOP' (which is off).

**Comment by trizmark** [comment] 2023-09-16 07:25
@videojedi Are you working on pymyenergi? I forked it as well, but let's not duplicate efforts.

**Comment by videojedi** [comment] 2023-09-16 07:57
Yes. I added the very basic libbi support in the last PR. Feel free to PR my fork. Or I can make you a direct collaborator?  Then we can PR the main repo when happy it works?Sent from my iPhoneOn 16 Sep 2023, at 08:25, Zoltan ***@***.***> wrote:﻿
@videojedi Are you working on pymyenergi? I forked it as well, but let's not duplicate efforts.

**Comment by simonjgreen** [comment] 2023-09-17 08:57
> @videojedi https://github.com/trizmark/ha-myenergi/tree/add-libbi-support Added SoC, voltage, frequency and some of the CTs. Will do some more work later.

I may be being blind, but was looking for where you added the CTs and can't see it in your commits. Mind sharing where that is? I have some time today so was going to test against mine.

**Comment by videojedi** [comment] 2023-09-17 09:13
> I may be being blind, but was looking for where you added the CTs and can't see it in your commits. Mind sharing where that is? I have some time today so was going to test against mine.

have a look in ha-myenergi/custom-components/myenergi/sensor.py lines 492-568

**Comment by trizmark** [comment] 2023-09-17 09:51
@videojedi Would you mind having a look at this line? https://github.com/videojedi/pymyenergi/blob/69e6a19e0f3b17c2275eb5eb9472176db11c4a06/pymyenergi/libbi.py#L184
That throws an error for me.

I have reworked the mode selection and will start updating the HA component.

**Comment by G6EJD** [comment] 2023-09-17 10:10
.get() needs two parameters - missing

**Comment by videojedi** [comment] 2023-09-17 11:09
removed for now..... still working out energy calcs.... 
added battery in an out values to cli energy

`myenergi libbi energy`

> generated: 2.39kWh
> grid_import: 12.31kWh
> grid_export: 0.15kWh
> battery_in: 1.22kWh
> battery_out: 2.33kWh
> pv_total: 0.0kWh
> device_boosted: 0.0kWh
> device_green: 0.0kWh
> device_total: 0.0kWh
> ct_internal_load: 0.0kWh
> ct_dcpv: 0.0kWh

although, pv_total is only provided on a minute by minute (/cgi-jday-), /cgi-jdayhour- does not include pvp1 values

**Comment by simonjgreen** [comment] 2023-09-17 12:58
We appear to be following the same track @videojedi :D
```% myenergi libbi energy
generated: 3.27kWh
grid_import: 17.26kWh
grid_export: 0.53kWh
device_boosted: 0.0kWh
device_green: 0.0kWh
device_total: 0.0kWh
device_charge: 12.87kWh
device_discharge: 10.91kWh
ct_internal_load: 0.0kWh
ct_grid: 0.0kWh
ct_dcpv: 0.0kWh

**Comment by videojedi** [comment] 2023-09-17 13:28
inverter export? as there is also ivi1 inverter import?

**Comment by simonjgreen** [comment] 2023-09-17 13:29
I'm not sure the `pvp1`/`ive1` values are especially useful. I've confirmed that `gep` matches my total solar generation, including solar though PV directly connected to libbi as well as solar monitored on two other inverters by CTs on eddis. The total generation is much more meaningful for home assistants context.

Adding in the bcp/bdp values eg
```
            "device_charge": round(energy_wh["bcp1"] / 1000, 2),
            "device_discharge": round(energy_wh["bdp1"] / 1000, 2)
```
and adding in the property values to libbi.py eg
```
    @property
    def energy_charge(self):
        """Device battery charged from history data"""
        return self.history_data.get("device_charge", 0)
    
    @property
    def energy_discharge(self):
        """Device battery discharged from history data"""
        return self.history_data.get("device_discharge", 0)
```

and then update ha-myenergi with two additional sensors eg
```
sensors.append(
    MyenergiSensor(
        coordinator,
        device,
        entry,
        create_energy_meta("Battery charged session", "energy_charge"),
    )
)
sensors.append(
    MyenergiSensor(
        coordinator,
        device,
        entry,
        create_energy_meta("Battery discharged session", "energy_discharge"),
    )
)
```

or similar...

is the next logical move.

**Comment by videojedi** [comment] 2023-09-17 14:11
looking at libbi in myenergi app. it would seem Libbi discharge is actually ive1 minus bdp1??

**Comment by simonjgreen** [comment] 2023-09-17 14:23
Hmm I am now unsure myself. Compare these:
```
[trimmed for brevity]
generated: 4.34kWh
grid_import: 17.29kWh
grid_export: 0.59kWh
device_charge[bcp1]: 12.88kWh
device_discharge[bdp1]: 12.44kWh
device_ive1: 14.8kWh
```
![image](https://github.com/CJNE/ha-myenergi/assets/615980/b178bbcd-cce1-42bf-b51c-45d2a5a453d6)

**Comment by videojedi** [comment] 2023-09-17 14:59
gray and cloudy here too... 

yes inconsistent....

<img width="631" alt="Pasted Graphic" src="https://github.com/CJNE/ha-myenergi/assets/7032506/63e166d2-8df6-44f6-a9fb-1bf20746283a">


generated: 6.3kWh
grid_import: 13.13kWh
grid_export: 0.36kWh
battery_charge: 1.58kWh
battery_discharge: 3.37kWh
inverter_export: 8.47kWh
inverter_import: 0.97kWh

**Comment by videojedi** [comment] 2023-09-17 15:18
So the request from the App is

> https://s18.myenergi.net/cgi-jday-Lxxxxxxxx-2023-9-16-23-0-1440

where as the pymyenergi (when using the energy option) is 

> https://s18.myenergi.net/cgi-jdayhour-Lxxxxxxxx-2023-9-17-0-24

So the app (despite being set to Today) is requesting minute by minute for 24 hours starting 11pm yesterday?

We are asking for hour by hour for today.......

**Comment by videojedi** [comment] 2023-09-17 16:48
confirmed by forcing request to same values.....

![image](https://github.com/CJNE/ha-myenergi/assets/7032506/676c4c0e-f0f6-43e9-8077-cb0f15f20665)

**Comment by trizmark** [comment] 2023-09-17 17:56
Finally, finally got stuff working. I spent most of my afternoon trying to figure out how to use a local copy of my updated pymyenergi module.
Mode change is working (and logged by HA):
![Screenshot 2023-09-17 at 18 48 14](https://github.com/CJNE/ha-myenergi/assets/36660435/1b05406f-db2b-46c1-a4dc-43d7c3a1dea2)

Also got the actual status in a sensor:

![Screenshot 2023-09-17 at 18 51 25](https://github.com/CJNE/ha-myenergi/assets/36660435/558cba8b-df10-4799-abd7-2a7f447eb5e0)

I am attaching the custom component if anybody wants to test it. (It's two repos cobbled together while we're working on the HA integration and the actual pymyenergi module)

[myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12643383/myenergi.tgz)

**Comment by videojedi** [comment] 2023-09-17 17:59
im struggling to work that out too!, how do you run update pymyenergi module iin home assistant?

**Comment by trizmark** [comment] 2023-09-17 18:04
If you look at the attached tgz you'll see that I included the pymyenergi under the myenergi dir.
I also modified the __init__.py of myenergi and added:
```
import sys
sys.path.insert(0, '/config/custom_components/myenergi')
```
before importing anything from pymyenergi.

**Comment by simonjgreen** [comment] 2023-09-17 18:16
I'd been trying to figure out the same thing 😆. I'd still like to understand what becomes of the modules from requirements.txt in HA.

> If you look at the attached tgz you'll see that I included the pymyenergi under the myenergi dir. I also modified the `__init__.py` of myenergi and added:
> 
> ```
> import sys
> sys.path.insert(0, '/config/custom_components/myenergi')
> ```
> 
> before importing anything from pymyenergi.

Are you sure you've uploaded the right tgz? I don't see that in there.

**Comment by videojedi** [comment] 2023-09-17 18:54
yep mode select works..... :)
Do you want to merge that back into main branch? and I'll merge in the battery energy stuff from today.

**Comment by trizmark** [comment] 2023-09-17 18:57
> I'd been trying to figure out the same thing 😆. I'd still like to understand what becomes of the modules from requirements.txt in HA.

They're installed via pip. 

> 
> Are you sure you've uploaded the right tgz? I don't see that in there.

Attaching the file again. Here's the listing:
```
% tar tvzf myenergi.tgz
drwxr-xr-x  0 root   root        0 17 Sep 18:43 myenergi/
-rw-r--r--  0 root   root      341 17 Sep 18:18 myenergi/manifest.json
-rw-r--r--  0 root   root    23972 17 Sep 18:41 myenergi/sensor.py
drwxr-xr-x  0 root   root        0 17 Sep 18:43 myenergi/__pycache__/
-rw-r--r--  0 root   root     9939 17 Sep 18:43 myenergi/__pycache__/select.cpython-311.pyc
-rw-r--r--  0 root   root    23650 17 Sep 18:43 myenergi/__pycache__/sensor.cpython-311.pyc
-rw-r--r--  0 root   root     9494 17 Sep 18:43 myenergi/__pycache__/number.cpython-311.pyc
-rw-r--r--  0 root   root     7079 17 Sep 18:43 myenergi/__pycache__/config_flow.cpython-311.pyc
-rw-r--r--  0 root   root     6101 17 Sep 18:43 myenergi/__pycache__/entity.cpython-311.pyc
-rw-r--r--  0 root   root     3733 17 Sep 18:43 myenergi/__pycache__/binary_sensor.cpython-311.pyc
-rw-r--r--  0 root   root     1023 17 Sep 18:43 myenergi/__pycache__/const.cpython-311.pyc
-rw-r--r--  0 root   root     7349 17 Sep 18:43 myenergi/__pycache__/__init__.cpython-311.pyc
-rw-r--r--  0 root   root     3254 14 Sep 17:08 myenergi/entity.py
drwxr-xr-x  0 root   root        0 17 Sep 10:07 myenergi/pymyenergi/
-rw-r--r--  0 root   root     5583 17 Sep 18:22 myenergi/pymyenergi/libbi.py
-rw-r--r--  0 root   root     1505 16 Sep 13:35 myenergi/pymyenergi/harvi.py
-rw-r--r--  0 root   root     7727 16 Sep 13:35 myenergi/pymyenergi/base_device.py
drwxr-xr-x  0 root   root        0 17 Sep 18:43 myenergi/pymyenergi/__pycache__/
-rw-r--r--  0 root   root    19962 17 Sep 10:07 myenergi/pymyenergi/__pycache__/zappi.cpython-311.pyc
-rw-r--r--  0 root   root     2598 17 Sep 10:07 myenergi/pymyenergi/__pycache__/exceptions.cpython-311.pyc
-rw-r--r--  0 root   root    14777 17 Sep 10:07 myenergi/pymyenergi/__pycache__/cli.cpython-311.pyc
-rw-r--r--  0 root   root     3157 17 Sep 10:07 myenergi/pymyenergi/__pycache__/harvi.cpython-311.pyc
-rw-r--r--  0 root   root    18691 17 Sep 10:07 myenergi/pymyenergi/__pycache__/client.cpython-311.pyc
-rw-r--r--  0 root   root    13773 17 Sep 10:07 myenergi/pymyenergi/__pycache__/base_device.cpython-311.pyc
-rw-r--r--  0 root   root     5795 17 Sep 10:07 myenergi/pymyenergi/__pycache__/connection.cpython-311.pyc
-rw-r--r--  0 root   root    10389 17 Sep 18:43 myenergi/pymyenergi/__pycache__/libbi.cpython-311.pyc
-rw-r--r--  0 root   root      570 17 Sep 10:07 myenergi/pymyenergi/__pycache__/__init__.cpython-311.pyc
-rw-r--r--  0 root   root    12695 17 Sep 10:07 myenergi/pymyenergi/__pycache__/eddi.cpython-311.pyc
-rw-r--r--  0 root   root      309 16 Sep 13:35 myenergi/pymyenergi/ct.py
-rw-r--r--  0 root   root      312 16 Sep 13:35 myenergi/pymyenergi/__init__.py
-rw-r--r--  0 root   root        6 17 Sep 18:20 myenergi/pymyenergi/VERSION
-rw-r--r--  0 root   root     9718 16 Sep 13:35 myenergi/pymyenergi/cli.py
-rw-r--r--  0 root   root     3566 16 Sep 13:35 myenergi/pymyenergi/connection.py
-rw-r--r--  0 root   root     1652 16 Sep 13:35 myenergi/pymyenergi/exceptions.py
-rw-r--r--  0 root   root     6856 16 Sep 13:35 myenergi/pymyenergi/eddi.py
-rw-r--r--  0 root   root    11022 16 Sep 13:35 myenergi/pymyenergi/zappi.py
-rw-r--r--  0 root   root    12007 16 Sep 13:35 myenergi/pymyenergi/client.py
-rw-r--r--  0 root   root     5063 15 Sep 13:22 myenergi/number.py
-rw-r--r--  0 root   root     5796 17 Sep 18:26 myenergi/select.py
drwxr-xr-x  0 root   root        0 17 Sep 18:42 myenergi/translations/
-rw-r--r--  0 root   root      868 14 Sep 17:08 myenergi/translations/nb.json
-rw-r--r--  0 root   root      822 14 Sep 17:08 myenergi/translations/sv.json
-rw-r--r--  0 root   root      895 14 Sep 17:08 myenergi/translations/de.json
-rw-r--r--  0 root   root      874 14 Sep 17:08 myenergi/translations/fr.json
-rw-r--r--  0 root   root      797 14 Sep 17:08 myenergi/translations/en.json
-rw-r--r--  0 root   root     3949 17 Sep 18:17 myenergi/__init__.py
-rw-r--r--  0 root   root      890 14 Sep 17:08 myenergi/const.py
-rw-r--r--  0 root   root     4234 14 Sep 17:08 myenergi/config_flow.py
-rw-r--r--  0 root   root     1256 14 Sep 17:08 myenergi/services.yaml
-rw-r--r--  0 root   root     2776 14 Sep 17:08 myenergi/binary_sensor.py
```
[myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12643513/myenergi.tgz)

**Comment by trizmark** [comment] 2023-09-17 19:05
> yep mode select works..... :) Do you want to merge that back into main branch? and I'll merge in the battery energy stuff from today.

Merged.
I'll have a look at the energy data once you merge it and expose it in the HA component.

**Comment by trizmark** [comment] 2023-09-18 10:17
I've got the energy data exposed now. Also moved some of the entities from diagnostic to sensors.
![Screenshot 2023-09-18 at 11 12 57](https://github.com/CJNE/ha-myenergi/assets/36660435/9e440c32-c6fd-4150-9e4e-aee8b1dac4d4)

The updated component + python package for those who want to test:
[myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12646664/myenergi.tgz)

**Comment by trizmark** [comment] 2023-09-18 18:17
Yeah, all that stuff is under the Diagnostic section.
![image](https://github.com/CJNE/ha-myenergi/assets/36660435/348a84a2-e1aa-4bd8-8e25-fd2550b6cf12)

I am fairly happy with it, so once I've done some more testing I'll issue a PR for pymyenergi first, then the HA component.
I've got plans to add the various calls to enable/disable battery discharge to eddi/zappi. Also enable/disable grid charging (once the bearer token stuff is worked out).
But I think it's in a good shape to call this version as 'support for libbi monitoring'. Feel free to disagree!

**Comment by videojedi** [comment] 2023-09-18 19:12
Amazing work! All good for me. 
There was some inconsistency between the daily charge totals of home assistant and the app. But pretty sure this was down to the app measuring 24hours from 11pm on the previous day, rather than midnight on the day requested.

Very happy with it. Please issue the PR when your happy too.

My end goal is to automate the overnight charging option when the solar prediction is showing poor weather for the following day. There must be a backend endpoint for switching grid charging on and off we just haven't found. But I guess only myenergi know what that is...... :)

**Comment by plord12** [comment] 2023-09-28 18:48
Well, I raised this issue ... today my libbi arrived, I installed this update and it worked first time !

Great work !

**Closed** 2023-10-04 13:42 UTC

**Comment by plord12** [comment] 2023-10-04 17:30
> I am attaching the custom component if anybody wants to test it. (It's two repos cobbled together while we're working on the HA integration and the actual pymyenergi module)
> 
> [myenergi.tgz](https://github.com/CJNE/ha-myenergi/files/12643383/myenergi.tgz)

I used this version for a while ( file size 77932 bytes ) but now the changes have merged, I've just switched to main.

I noticed that sensor.myenergi_libbi_home_consumption and sensor.myenergi_libbi_power_charging have gone.

Not really a problem, since I think both of these can be calculated in home assistant, but just wanted to check that this was intentional.
